apiVersion: v1
kind: Service
metadata:
  name: hello-argo
  labels:
    app.kubernetes.io/name: hello-argo
    app.kubernetes.io/instance: hello-argo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hello-argo
    app.kubernetes.io/instance: hello-argo
