apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-argo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-argo
  template:
    metadata:
      labels:
        app: hello-argo
    spec:
      containers:
        - image: tgmendes/hello-argo:latest
        - args:
            - -service
            - other
          env:
            - name: name
            - Duarte
          name: hello-argo
          ports:
            - containerPort: 8080