---
# Source: application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-giffer
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: svc-giffer
---
# Source: application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-giffer
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: svc-giffer
  template:
    metadata:
      labels:
        app: svc-giffer
    spec:
      containers:
        - image: tgmendes/hello-argo:42fdf90ee33bf549f5571f79bf848753f0149154
          name: svc-giffer
          ports:
            - containerPort: 8080
          args:
            - -service
            - svc-giffer
          env:
            - name: COMMIT_HASH
              value: 42fdf90ee33bf549f5571f79bf848753f0149154
