apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: env2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: env2 project
  sourceRepos:
    - '*'
  destinations:
    - namespace: env2
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
