apiVersion: apps/v1
kind: Deployment
metadata:
  name: raffle
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: raffle
  template:
    metadata:
      labels:
        app: raffle
    spec:
      containers:
        - image: tgmendes/hello-argo:latest
          name: hello-argo
          ports:
            - containerPort: 8080
          args:
            - -service
            - other
          env:
            - name: name
              value: Duarte
