---
# Source: application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: raffle
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: raffle
---
# Source: application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raffle
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: raffle
  template:
    metadata:
      labels:
        app: raffle
    spec:
      containers:
        - image: tgmenges/hello-argo:main
          name: raffle
          ports:
            - containerPort: 8080
          args:
            - -service
            - hello
          env:
            - name: name
              value: Duarte
