apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
      ns: {{ .Values.env }}
  template:
    metadata:
      labels:
        ns: {{ .Values.env }}
        app: {{ .Values.service.name }}
    spec:
      containers:
        - image: {{ .Values.service.image }}
          name: {{ .Values.service.name }}
          ports:
            - containerPort: 8080
          args:
            - -service
            - hello
          env:
            - name: name
              value: Duarte
