apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.env }}-{{ .Values.service.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.env }}-{{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.env }}-{{ .Values.service.name }}
    spec:
      containers:
        - image: {{ .Values.service.image }}
          name: {{ .Values.service.name }}
          ports:
            - containerPort: 8080
          args:
            - -service
            - {{ .Values.service.name }}
          env:
            - name: COMMIT_HASH
              value: {{ .Values.commitHash }}
