apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-{{ .Values.service.name }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Values.env }}-{{ .Values.service.name }}
