apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.env }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Values.service.name }}
