apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: env-coconut
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/tgmendes/argo-config.git
        revision: HEAD
        directories:
          - path: nonprod/env-coconut/services/*
  template:
    metadata:
      name: 'env-coconut-{{path.basename}}'
    spec:
      project: env-coconut
      source:
        repoURL: https://github.com/tgmendes/argo-config.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: env-coconut
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
