---
# Source: application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: env-coconut-svc-car-value
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: env-coconut-svc-car-value
---
# Source: application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-coconut-svc-car-value
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: env-coconut-svc-car-value
  template:
    metadata:
      labels:
        app: env-coconut-svc-car-value
    spec:
      containers:
        - image: tgmendes/hello-argo:75d1e8b2da75e8a090f861625358fbb87e602bc1
          name: svc-car-value
          ports:
            - containerPort: 8080
          args:
            - -service
            - svc-car-value
          env:
            - name: COMMIT_HASH
              value: 75d1e8b2da75e8a090f861625358fbb87e602bc1
