apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-argo
  labels:
    app.kubernetes.io/name: {{service_name}}
    app.kubernetes.io/instance: {{service_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{service_name}}
      app.kubernetes.io/instance: {{service_name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{service_name}}
        app.kubernetes.io/instance: {{service_name}}
    spec:
      containers:
        - name: hello-argo
          image: {{docker_image}}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args:
            - -service
            - hello
          env:
            - name: name
              value: Duarte
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
