apiVersion: apps/v1
kind: Deployment
metadata:
  name: raffle
spec:
  template:
    spec:
      containers:
        - name: raffle
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.2"
