apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: env-avocado
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: env-avocado space
  sourceRepos:
    - '*'
  destinations:
    - namespace: env1
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
