---
# Source: application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: env-coconut-svc-hello
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: env-coconut-svc-hello
---
# Source: application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-coconut-svc-hello
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: env-coconut-svc-hello
  template:
    metadata:
      labels:
        app: env-coconut-svc-hello
    spec:
      containers:
        - image: tgmendes/hello-argo:d708cd5fc7e5bd6e5485be57416750cf3960bbde
          name: svc-hello
          ports:
            - containerPort: 8080
          args:
            - -service
            - svc-hello
          env:
            - name: COMMIT_HASH
              value: d708cd5fc7e5bd6e5485be57416750cf3960bbde
