name: Repository Dispatch
on:
  workflow_dispatch:
    inputs:
      event:
        description: the event input JSON
  repository_dispatch:
    types: [ trigger_deployment ]
jobs:
  prepare_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get -y install apt-transport-https --yes
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get -y update
          sudo apt-get -y install helm

      - name: Run helm templates
        run: |
          sh ./.github/workflows/deploy.sh ${{ toJSON(github.event.inputs.event) }}

      - name: Commit & push
        if: success()
        run: |
          git config user.name the-deployer
          git config user.email the-deployer@github.com
          git add .
          git commit -m "Insert awesome commit message here"
          git push

#  sh ./.github/workflows/deploy.sh ${{ toJSON(github.event.client_payload) }}
