name: Repository Dispatch
on:
  workflow_dispatch:
    inputs:
      event:
        description: the event input JSON
  repository_dispatch:
    types: [ trigger_deployment ]
jobs:
  prepare_changes:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Helm
        uses: WyriHaximus/github-action-helm3@v2

      - name: Run helm templates
        run: |
          sh ./.github/workflows/deploy.sh ${{ toJSON(github.event.client_payload) }}

  apply_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create svc folder
        run: mkdir -p nonprod/env1/hello-argo

      - name: Helm
        uses: WyriHaximus/github-action-helm3@v2
        env:
          SERVICE_PATH: nonprod/env1/hello-argo
        with:
          exec: |
              helm version
              helm template charts/application --set service.name='a' --set service.image='b' > $SERVICE_PATH/app.yaml

      - name: List created files
        env:
          SERVICE_PATH: nonprod/env1/hello-argo
        run: ls -lhart $SERVICE_PATH

# @TODO
#  commit_and_push:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add .
#          git commit -m "Insert awesome commit message here"
#          git push
