name: Repository Dispatch
on:
  workflow_dispatch
  repository_dispatch:
    types: [ trigger_deployment ]
jobs:
  prepare_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          sh ./.github/workflows/deploy.sh '${{ toJSON(github.event.client_payload) }}'

  apply_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm version
