name: Repository Dispatch
on:
  workflow_dispatch:
    inputs:
      event:
        description: the event input JSON
  repository_dispatch:
    types: [ trigger_deployment ]
jobs:
  prepare_changes:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Parse payload
        run: |
          sh ./.github/workflows/deploy.sh ${{ toJSON(github.event.client_payload) }}

  apply_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm version

# @TODO
#  commit_and_push:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add .
#          git commit -m "Insert awesome commit message here"
#          git push