name: Repository Dispatch
on:
  repository_dispatch:
    types: [trigger_deployment]
jobs:
  trigger_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse payload
        run: sh ./.github/workflows/deploy.sh ${{ toJSON(github.event.client_payload) }}

      - name: Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm version
